#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

trap "exit" INT
for fullfile in $DIR/../data/problem_*; do
    filename=$(basename "$fullfile")
    filename="${filename%.*}"
    echo $filename
    time $1 -c $2 -p "ei!" -f "$fullfile" > "$DIR/../solutions/${filename}_solution.json"
done
